//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TnT.RFXProcessMsgService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class ExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultType resultField;
        
        private ExceptionType causeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultType result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExceptionType cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class ResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private LanguageDependentStringType msgField;
        
        private NameValueListType paramListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LanguageDependentStringType msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NameValueListType paramList {
            get {
                return this.paramListField;
            }
            set {
                this.paramListField = value;
                this.RaisePropertyChanged("paramList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageDependentStringWithDefaultLanguageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class LanguageDependentStringType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryHexType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2004/11/xmlmime")]
    public partial class hexBinary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class BinaryHexType : hexBinary {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryBase64Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2004/11/xmlmime")]
    public partial class base64Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class BinaryBase64Type : base64Binary {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypedQualifiedIdType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class QualifiedIdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qlfrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qlfr {
            get {
                return this.qlfrField;
            }
            set {
                this.qlfrField = value;
                this.RaisePropertyChanged("qlfr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class TypedQualifiedIdType : QualifiedIdType {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class DocumentUrlType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/2004/11/xmlmime")]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamedDocumentContainerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class DocumentContainerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("binaryBase64", typeof(BinaryBase64Type), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("binaryHex", typeof(BinaryHexType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("docId", typeof(QualifiedIdType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("docUrl", typeof(DocumentUrlType), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class NamedDocumentContainerType : DocumentContainerType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class NamedValueListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] valField;
        
        private string nameField;
        
        private string typeField;
        
        private string qlfrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("val", Order=0)]
        public string[] val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
                this.RaisePropertyChanged("val");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qlfr {
            get {
                return this.qlfrField;
            }
            set {
                this.qlfrField = value;
                this.RaisePropertyChanged("qlfr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class NamedValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        private string qlfrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qlfr {
            get {
                return this.qlfrField;
            }
            set {
                this.qlfrField = value;
                this.RaisePropertyChanged("qlfr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamedTypedIdListType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedNamedTypedIdListType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedTypedOptionallyQualifiedIdListType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class TypedOptionallyQualifiedIdListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OptionallyTypedOptionallyQualifiedIdType[] idField;
        
        private string typeField;
        
        private string qlfrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", Order=0)]
        public OptionallyTypedOptionallyQualifiedIdType[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qlfr {
            get {
                return this.qlfrField;
            }
            set {
                this.qlfrField = value;
                this.RaisePropertyChanged("qlfr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class OptionallyTypedOptionallyQualifiedIdType : OptionallyQualifiedIdType {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionalRelationshipOptionallyQualifiedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypedOptionallyQualifiedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamedTypedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedNamedTypedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedTypedOptionallyQualifiedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionallyTypedOptionallyQualifiedIdType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class OptionallyQualifiedIdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qlfrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qlfr {
            get {
                return this.qlfrField;
            }
            set {
                this.qlfrField = value;
                this.RaisePropertyChanged("qlfr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class OptionalRelationshipOptionallyQualifiedIdType : OptionallyQualifiedIdType {
        
        private string relIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relId {
            get {
                return this.relIdField;
            }
            set {
                this.relIdField = value;
                this.RaisePropertyChanged("relId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamedTypedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedNamedTypedIdType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedTypedOptionallyQualifiedIdType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class TypedOptionallyQualifiedIdType : OptionallyQualifiedIdType {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedNamedTypedIdType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class NamedTypedIdType : TypedOptionallyQualifiedIdType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class RelatedNamedTypedIdType : NamedTypedIdType {
        
        private string relTypeField;
        
        private string relActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relType {
            get {
                return this.relTypeField;
            }
            set {
                this.relTypeField = value;
                this.RaisePropertyChanged("relType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relAction {
            get {
                return this.relActionField;
            }
            set {
                this.relActionField = value;
                this.RaisePropertyChanged("relAction");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class RelatedTypedOptionallyQualifiedIdType : TypedOptionallyQualifiedIdType {
        
        private string relTypeField;
        
        private string relActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relType {
            get {
                return this.relTypeField;
            }
            set {
                this.relTypeField = value;
                this.RaisePropertyChanged("relType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relAction {
            get {
                return this.relActionField;
            }
            set {
                this.relActionField = value;
                this.RaisePropertyChanged("relAction");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedNamedTypedIdListType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class NamedTypedIdListType : TypedOptionallyQualifiedIdListType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class RelatedNamedTypedIdListType : NamedTypedIdListType {
        
        private string relTypeField;
        
        private string relActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relType {
            get {
                return this.relTypeField;
            }
            set {
                this.relTypeField = value;
                this.RaisePropertyChanged("relType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relAction {
            get {
                return this.relActionField;
            }
            set {
                this.relActionField = value;
                this.RaisePropertyChanged("relAction");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class RelatedTypedOptionallyQualifiedIdListType : TypedOptionallyQualifiedIdListType {
        
        private string relTypeField;
        
        private string relActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relType {
            get {
                return this.relTypeField;
            }
            set {
                this.relTypeField = value;
                this.RaisePropertyChanged("relType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relAction {
            get {
                return this.relActionField;
            }
            set {
                this.relActionField = value;
                this.RaisePropertyChanged("relAction");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class NameValueListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string nameField;
        
        private string typeField;
        
        private string qlfrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("docCont", typeof(NamedDocumentContainerType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(NamedTypedIdType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("idList", typeof(NamedTypedIdListType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("nameValList", typeof(NameValueListType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("relId", typeof(RelatedNamedTypedIdType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("relIdList", typeof(RelatedNamedTypedIdListType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("val", typeof(NamedValueType), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valList", typeof(NamedValueListType), IsNullable=true, Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qlfr {
            get {
                return this.qlfrField;
            }
            set {
                this.qlfrField = value;
                this.RaisePropertyChanged("qlfr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiIoBaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class VoidType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public abstract partial class ApiIoBaseType : VoidType {
        
        private string contentStructVerField;
        
        private System.DateTime createDateTimeField;
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentStructVer {
            get {
                return this.contentStructVerField;
            }
            set {
                this.contentStructVerField = value;
                this.RaisePropertyChanged("contentStructVer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime createDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
                this.RaisePropertyChanged("createDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public abstract partial class ApiResponseType : ApiIoBaseType {
        
        private ResultType resultField;
        
        private string responseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultType result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public abstract partial class ApiRequestType : ApiIoBaseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class LanguageDependentStringWithDefaultLanguageType : LanguageDependentStringType {
        
        private bool defaultField;
        
        public LanguageDependentStringWithDefaultLanguageType() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
                this.RaisePropertyChanged("default");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", ConfigurationName="RFXProcessMsgService.IMessagingService")]
    public interface IMessagingService {
        
        // CODEGEN: Generating message contract since the operation testService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsop.rfxcel.com/messagingService/3/testService", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TnT.RFXProcessMsgService.ExceptionType), Action="http://wsop.rfxcel.com/messagingService/3/testService", Name="exception", Namespace="http://xmlns.rfxcel.com/traceability/3")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hexBinary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base64Binary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentContainerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TypedOptionallyQualifiedIdListType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OptionallyQualifiedIdType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VoidType))]
        TnT.RFXProcessMsgService.testServiceResponse1 testService(TnT.RFXProcessMsgService.testServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsop.rfxcel.com/messagingService/3/testService", ReplyAction="*")]
        System.Threading.Tasks.Task<TnT.RFXProcessMsgService.testServiceResponse1> testServiceAsync(TnT.RFXProcessMsgService.testServiceRequest request);
        
        // CODEGEN: Generating message contract since the operation processMessages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsop.rfxcel.com/messagingService/3/processMessages", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TnT.RFXProcessMsgService.ExceptionType), Action="http://wsop.rfxcel.com/messagingService/3/processMessages", Name="exception", Namespace="http://xmlns.rfxcel.com/traceability/3")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hexBinary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base64Binary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentContainerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TypedOptionallyQualifiedIdListType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OptionallyQualifiedIdType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VoidType))]
        TnT.RFXProcessMsgService.processMessagesResponse1 processMessages(TnT.RFXProcessMsgService.processMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsop.rfxcel.com/messagingService/3/processMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<TnT.RFXProcessMsgService.processMessagesResponse1> processMessagesAsync(TnT.RFXProcessMsgService.processMessagesRequest request);
        
        // CODEGEN: Generating message contract since the operation getMessages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsop.rfxcel.com/messagingService/3/getMessages", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TnT.RFXProcessMsgService.ExceptionType), Action="http://wsop.rfxcel.com/messagingService/3/getMessages", Name="exception", Namespace="http://xmlns.rfxcel.com/traceability/3")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hexBinary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base64Binary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentContainerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TypedOptionallyQualifiedIdListType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OptionallyQualifiedIdType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VoidType))]
        TnT.RFXProcessMsgService.getMessagesResponse1 getMessages(TnT.RFXProcessMsgService.getMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsop.rfxcel.com/messagingService/3/getMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<TnT.RFXProcessMsgService.getMessagesResponse1> getMessagesAsync(TnT.RFXProcessMsgService.getMessagesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3")]
    public partial class testService : ApiRequestType {
        
        private string testNameField;
        
        private NameValueListType paramListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string testName {
            get {
                return this.testNameField;
            }
            set {
                this.testNameField = value;
                this.RaisePropertyChanged("testName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameValueListType paramList {
            get {
                return this.paramListField;
            }
            set {
                this.paramListField = value;
                this.RaisePropertyChanged("paramList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3")]
    public partial class testServiceResponse : ApiResponseType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", Order=0)]
        public TnT.RFXProcessMsgService.testService testService;
        
        public testServiceRequest() {
        }
        
        public testServiceRequest(TnT.RFXProcessMsgService.testService testService) {
            this.testService = testService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testServiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", Order=0)]
        public TnT.RFXProcessMsgService.testServiceResponse testServiceResponse;
        
        public testServiceResponse1() {
        }
        
        public testServiceResponse1(TnT.RFXProcessMsgService.testServiceResponse testServiceResponse) {
            this.testServiceResponse = testServiceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3")]
    public partial class processMessages : ApiRequestType {
        
        private EnvelopeType[] msgEnvelopeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("envelope", Namespace="http://xmlns.rfxcel.com/traceability/api/3", IsNullable=false)]
        public EnvelopeType[] msgEnvelopeList {
            get {
                return this.msgEnvelopeListField;
            }
            set {
                this.msgEnvelopeListField = value;
                this.RaisePropertyChanged("msgEnvelopeList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public partial class EnvelopeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnvelopeHeaderType headerField;
        
        private EnvelopeBodyType bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnvelopeHeaderType header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EnvelopeBodyType body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public partial class EnvelopeHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageInfoType msgInfoField;
        
        private MessageInfoType origMsgInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageInfoType msgInfo {
            get {
                return this.msgInfoField;
            }
            set {
                this.msgInfoField = value;
                this.RaisePropertyChanged("msgInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessageInfoType origMsgInfo {
            get {
                return this.origMsgInfoField;
            }
            set {
                this.origMsgInfoField = value;
                this.RaisePropertyChanged("origMsgInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public partial class MessageInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QualifiedIdType sysDeploymentIdField;
        
        private QualifiedIdType senderInstIdField;
        
        private TypedQualifiedIdType senderIdField;
        
        private QualifiedIdType receiverInstIdField;
        
        private TypedQualifiedIdType receiverIdField;
        
        private OptionallyVersionedEnumType msgFormatField;
        
        private OptionallyVersionedEnumType msgTypeField;
        
        private OptionallyQualifiedIdType msgIdField;
        
        private OptionallyQualifiedIdType corrMsgIdField;
        
        private string fileNameField;
        
        private NameValueListType msgHeaderListField;
        
        private int msgPriorityField;
        
        private bool msgPriorityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QualifiedIdType sysDeploymentId {
            get {
                return this.sysDeploymentIdField;
            }
            set {
                this.sysDeploymentIdField = value;
                this.RaisePropertyChanged("sysDeploymentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QualifiedIdType senderInstId {
            get {
                return this.senderInstIdField;
            }
            set {
                this.senderInstIdField = value;
                this.RaisePropertyChanged("senderInstId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TypedQualifiedIdType senderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("senderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public QualifiedIdType receiverInstId {
            get {
                return this.receiverInstIdField;
            }
            set {
                this.receiverInstIdField = value;
                this.RaisePropertyChanged("receiverInstId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TypedQualifiedIdType receiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
                this.RaisePropertyChanged("receiverId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public OptionallyVersionedEnumType msgFormat {
            get {
                return this.msgFormatField;
            }
            set {
                this.msgFormatField = value;
                this.RaisePropertyChanged("msgFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public OptionallyVersionedEnumType msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public OptionallyQualifiedIdType msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public OptionallyQualifiedIdType corrMsgId {
            get {
                return this.corrMsgIdField;
            }
            set {
                this.corrMsgIdField = value;
                this.RaisePropertyChanged("corrMsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public NameValueListType msgHeaderList {
            get {
                return this.msgHeaderListField;
            }
            set {
                this.msgHeaderListField = value;
                this.RaisePropertyChanged("msgHeaderList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                this.msgPriorityField = value;
                this.RaisePropertyChanged("msgPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgPrioritySpecified {
            get {
                return this.msgPriorityFieldSpecified;
            }
            set {
                this.msgPriorityFieldSpecified = value;
                this.RaisePropertyChanged("msgPrioritySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/3")]
    public partial class OptionallyVersionedEnumType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string verField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ver {
            get {
                return this.verField;
            }
            set {
                this.verField = value;
                this.RaisePropertyChanged("ver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.rfxcel.com/traceability/api/3")]
    public partial class EnvelopeBodyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3")]
    public partial class processMessagesResponse : ApiResponseType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", Order=0)]
        public TnT.RFXProcessMsgService.processMessages processMessages;
        
        public processMessagesRequest() {
        }
        
        public processMessagesRequest(TnT.RFXProcessMsgService.processMessages processMessages) {
            this.processMessages = processMessages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processMessagesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", Order=0)]
        public TnT.RFXProcessMsgService.processMessagesResponse processMessagesResponse;
        
        public processMessagesResponse1() {
        }
        
        public processMessagesResponse1(TnT.RFXProcessMsgService.processMessagesResponse processMessagesResponse) {
            this.processMessagesResponse = processMessagesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3")]
    public partial class getMessages : ApiRequestType {
        
        private MessageInfoType msgInfoField;
        
        private NameValueListType selCriteriaListField;
        
        private string selOperatorField;
        
        private int msgCountField;
        
        private bool changeMsgStatusField;
        
        private bool changeMsgStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageInfoType msgInfo {
            get {
                return this.msgInfoField;
            }
            set {
                this.msgInfoField = value;
                this.RaisePropertyChanged("msgInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameValueListType selCriteriaList {
            get {
                return this.selCriteriaListField;
            }
            set {
                this.selCriteriaListField = value;
                this.RaisePropertyChanged("selCriteriaList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string selOperator {
            get {
                return this.selOperatorField;
            }
            set {
                this.selOperatorField = value;
                this.RaisePropertyChanged("selOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int msgCount {
            get {
                return this.msgCountField;
            }
            set {
                this.msgCountField = value;
                this.RaisePropertyChanged("msgCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool changeMsgStatus {
            get {
                return this.changeMsgStatusField;
            }
            set {
                this.changeMsgStatusField = value;
                this.RaisePropertyChanged("changeMsgStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changeMsgStatusSpecified {
            get {
                return this.changeMsgStatusFieldSpecified;
            }
            set {
                this.changeMsgStatusFieldSpecified = value;
                this.RaisePropertyChanged("changeMsgStatusSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3")]
    public partial class getMessagesResponse : ApiResponseType {
        
        private EnvelopeType[] msgEnvelopeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("envelope", Namespace="http://xmlns.rfxcel.com/traceability/api/3", IsNullable=false)]
        public EnvelopeType[] msgEnvelopeList {
            get {
                return this.msgEnvelopeListField;
            }
            set {
                this.msgEnvelopeListField = value;
                this.RaisePropertyChanged("msgEnvelopeList");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", Order=0)]
        public TnT.RFXProcessMsgService.getMessages getMessages;
        
        public getMessagesRequest() {
        }
        
        public getMessagesRequest(TnT.RFXProcessMsgService.getMessages getMessages) {
            this.getMessages = getMessages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.rfxcel.com/traceability/messagingService/3", Order=0)]
        public TnT.RFXProcessMsgService.getMessagesResponse getMessagesResponse;
        
        public getMessagesResponse1() {
        }
        
        public getMessagesResponse1(TnT.RFXProcessMsgService.getMessagesResponse getMessagesResponse) {
            this.getMessagesResponse = getMessagesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagingServiceChannel : TnT.RFXProcessMsgService.IMessagingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingServiceClient : System.ServiceModel.ClientBase<TnT.RFXProcessMsgService.IMessagingService>, TnT.RFXProcessMsgService.IMessagingService {
        
        public MessagingServiceClient() {
        }
        
        public MessagingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TnT.RFXProcessMsgService.testServiceResponse1 TnT.RFXProcessMsgService.IMessagingService.testService(TnT.RFXProcessMsgService.testServiceRequest request) {
            return base.Channel.testService(request);
        }
        
        public TnT.RFXProcessMsgService.testServiceResponse testService(TnT.RFXProcessMsgService.testService testService1) {
            TnT.RFXProcessMsgService.testServiceRequest inValue = new TnT.RFXProcessMsgService.testServiceRequest();
            inValue.testService = testService1;
            TnT.RFXProcessMsgService.testServiceResponse1 retVal = ((TnT.RFXProcessMsgService.IMessagingService)(this)).testService(inValue);
            return retVal.testServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TnT.RFXProcessMsgService.testServiceResponse1> TnT.RFXProcessMsgService.IMessagingService.testServiceAsync(TnT.RFXProcessMsgService.testServiceRequest request) {
            return base.Channel.testServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<TnT.RFXProcessMsgService.testServiceResponse1> testServiceAsync(TnT.RFXProcessMsgService.testService testService) {
            TnT.RFXProcessMsgService.testServiceRequest inValue = new TnT.RFXProcessMsgService.testServiceRequest();
            inValue.testService = testService;
            return ((TnT.RFXProcessMsgService.IMessagingService)(this)).testServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TnT.RFXProcessMsgService.processMessagesResponse1 TnT.RFXProcessMsgService.IMessagingService.processMessages(TnT.RFXProcessMsgService.processMessagesRequest request) {
            return base.Channel.processMessages(request);
        }
        
        public TnT.RFXProcessMsgService.processMessagesResponse processMessages(TnT.RFXProcessMsgService.processMessages processMessages1) {
            TnT.RFXProcessMsgService.processMessagesRequest inValue = new TnT.RFXProcessMsgService.processMessagesRequest();
            inValue.processMessages = processMessages1;
            TnT.RFXProcessMsgService.processMessagesResponse1 retVal = ((TnT.RFXProcessMsgService.IMessagingService)(this)).processMessages(inValue);
            return retVal.processMessagesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TnT.RFXProcessMsgService.processMessagesResponse1> TnT.RFXProcessMsgService.IMessagingService.processMessagesAsync(TnT.RFXProcessMsgService.processMessagesRequest request) {
            return base.Channel.processMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TnT.RFXProcessMsgService.processMessagesResponse1> processMessagesAsync(TnT.RFXProcessMsgService.processMessages processMessages) {
            TnT.RFXProcessMsgService.processMessagesRequest inValue = new TnT.RFXProcessMsgService.processMessagesRequest();
            inValue.processMessages = processMessages;
            return ((TnT.RFXProcessMsgService.IMessagingService)(this)).processMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TnT.RFXProcessMsgService.getMessagesResponse1 TnT.RFXProcessMsgService.IMessagingService.getMessages(TnT.RFXProcessMsgService.getMessagesRequest request) {
            return base.Channel.getMessages(request);
        }
        
        public TnT.RFXProcessMsgService.getMessagesResponse getMessages(TnT.RFXProcessMsgService.getMessages getMessages1) {
            TnT.RFXProcessMsgService.getMessagesRequest inValue = new TnT.RFXProcessMsgService.getMessagesRequest();
            inValue.getMessages = getMessages1;
            TnT.RFXProcessMsgService.getMessagesResponse1 retVal = ((TnT.RFXProcessMsgService.IMessagingService)(this)).getMessages(inValue);
            return retVal.getMessagesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TnT.RFXProcessMsgService.getMessagesResponse1> TnT.RFXProcessMsgService.IMessagingService.getMessagesAsync(TnT.RFXProcessMsgService.getMessagesRequest request) {
            return base.Channel.getMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TnT.RFXProcessMsgService.getMessagesResponse1> getMessagesAsync(TnT.RFXProcessMsgService.getMessages getMessages) {
            TnT.RFXProcessMsgService.getMessagesRequest inValue = new TnT.RFXProcessMsgService.getMessagesRequest();
            inValue.getMessages = getMessages;
            return ((TnT.RFXProcessMsgService.IMessagingService)(this)).getMessagesAsync(inValue);
        }
    }
}
